name: push

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 1
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          java-version: 17
          distribution: oracle
      - run: |
          ./gradlew build
          ./gradlew combinedjavadoc
          ./gradlew combinedWindowsZip
          ./gradlew combinedLinuxZip
          ./gradlew combinedrpm
          ./gradlew combineddeb
