name: push

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 1
      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: 17
          distribution: oracle
      - run: |
          ./gradlew build
          ./gradlew combinedjavadoc
          ./gradlew combinedWindowsZip
          ./gradlew combinedLinuxZip
          ./gradlew combinedrpm
          ./gradlew combineddeb
