name: push

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 1
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          java-version: 17
          distribution: oracle
      - run: |
          ./gradlew build
          ./gradlew combinedjavadoc
          ./gradlew combinedWindowsZip
          ./gradlew combinedLinuxZip
          ./gradlew combinedrpm
          ./gradlew combineddeb
